#
# application-hazelcast.yml
#
# This is the "hazelcast" profile to integrate with Hazcelcast.
# 

# Hazelcast
spring:
  cache:
    type: hazelcast
  jpa:
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
          hazelcast:
            use_native_client: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory